<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FamiliesToPersons" nsURI="platform:/plugin/FamiliesToPersons/model/FamiliesToPersons.ecore"
    nsPrefix="FamiliesToPersons">
  <eClassifiers xsi:type="ecore:EClass" name="FamilyMemberToPerson" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/FamiliesModel/model/FamiliesModel.ecore#//FamilyMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/PersonsModel/model/PersonsModel.ecore#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FamiliesToPersonsCorr" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/FamiliesModel/model/FamiliesModel.ecore#//Families"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/PersonsModel/model/PersonsModel.ecore#//Persons"/>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/FamiliesToPersons/model/FamiliesToPersons.ecore#//Rules"
      nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="FatherToMale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExistingFamily2Person" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="DaughterOfExistingFamilyToFemale"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SonOfExistingFamilyToMale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MotherOfExistingFamilyToFemale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FamilyMember2Person" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SonToMale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="DaughterToFemale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="MotherToFemale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FatherOfExistingFamilyToMale" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="Families2Persons" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
  </eSubpackages>
</ecore:EPackage>
