package org.benchmarx.familiestopersons;

public enum Decisions {
	PREFER_CREATING_FATHER_OVER_SON,
	PREFER_CREATING_MOTHER_OVER_DAUGHTER, 
	PREFER_EXISTINGMother_FAMILY_TO_NEW, 
	PREFER_EXISTINGDaughter_FAMILY_TO_NEW, 
	PREFER_EXISTINGFather_FAMILY_TO_NEW
}
